name: Build iOS App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest  # Cần dùng macOS để build iOS app

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          npm install
        continue-on-error: false

      - name: Install CocoaPods
        run: |
          cd ios
          pod install --repo-update

      - name: Build iOS App
        run: |
          cd ios
          xcodebuild -workspace articleCICD.xcworkspace \
                     -scheme articleCICD \
                     -sdk iphoneos \
                     -configuration Release \
                     -destination "generic/platform=iOS" \
                     archive -archivePath build/articleCICD.xcarchive

      - name: Export IPA
        run: |
          cd ios
          xcodebuild -exportArchive \
                     -archivePath build/articleCICD.xcarchive \
                     -exportOptionsPlist exportOptions.plist \
                     -exportPath build

      - name: Upload iOS Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: ios/build/*.ipa
